### ISSUE TITLE
2.2.1-2.2.3版本导出pdf报空引用错误

### ISSUE THREAD

**Issue by uncmd** [dotnetcore/Magicodes.IE#105]
**Describe the bug**
2.2.1-2.2.3版本导出pdf报空引用错误

   at RazorEngine.Compilation.CompilerServiceBase.GenerateCodeFile(String generatedCode, RazorProjectItem razorProjectItem)
   at RazorEngine.Compilation.CompilerServiceBase.GetGeneratorResult(IEnumerable`1 namespaces, TypeContext context)
   at RazorEngine.Compilation.CompilerServiceBase.GetCodeCompileUnit(TypeContext context)
   at RazorEngine.Roslyn.CSharp.RoslynCompilerServiceBase.CompileType(TypeContext context)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at Magicodes.ExporterAndImporter.Html.HtmlExporter.RunCompileTpl(Object model, String htmlTemplate)
   at Magicodes.ExporterAndImporter.Html.HtmlExporter.ExportListByTemplate[T](ICollection`1 dataItems, String htmlTemplate)
   at Magicodes.ExporterAndImporter.Pdf.PdfExporter.<ExportListByTemplate>d__1`1.MoveNext()

**Comment by hueifeng** [comment]
@uncmd  The problem cannot be reproduced, can you provide a demo, and can also provide code that allows me to reproduce.
我未能成功复现该问题，能否提供相关demo或者说可以提供给我可以复现问题的代码？

**Comment by uncmd** [comment]
static async Task Main(string[] args)
        {
            Console.WriteLine("开始导出PDF...");

            await ExportPdf();

            Console.WriteLine("导出完成...");
        }

        public static async Task ExportPdf()
        {
            var exporter = new PdfExporter();
            var result = await exporter.ExportListByTemplate("test.pdf", new List<Student>()
            {
                new Student
                {
                    Name = "AR.A",
                    Age = 18
                },
                new Student
                {
                    Name = "AR.B",
                    Age = 19
                },
                new Student
                {
                    Name = "AR.C",
                    Age = 20
                },
            });
        }
    }

    [PdfExporter(Name = "学生信息", IsWriteHtml = true, IsEnablePagesCount = true)]
    public class Student
    { 
        [ExporterHeader(DisplayName = "姓名")]
        [Display(Name = "Display姓名")]
        public string Name { get; set; } 
        
        [ExporterHeader(DisplayName = "年龄")]
        public int Age { get; set; } 
    }
