### ISSUE TITLE
centos 下导出PDf 出错  Unable to load shared library 'wkhtmltox' or one of its dependencies.

### ISSUE THREAD

**Issue by cnmediar** [dotnetcore/Magicodes.IE#125]
![image](https://user-images.githubusercontent.com/18731551/86554189-7b621a00-bf7f-11ea-9663-fad6dac60fbe.png)

**Screenshots**

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Unable to load shared library 'wkhtmltox' or one of its dependencies. In order to help diagnose G environment variable: libwkhtmltox: cannot open shared object file: No such file or directory)) ---> System.AggregateException: One or more errors occurred. (Unable to load shared l In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwkhtmltox: cannot open shared object file: No such file or directory) ---> System.Drary 'wkhtmltox' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libwkhtmltox: cannot open shared object fi
   at DinkToPdf.WkHtmlToXBindings.wkhtmltopdf_init(Int32 useGraphics)
   at DinkToPdf.WkHtmlModule.wkhtmltopdf_init(Int32 useGraphics)
   at DinkToPdf.PdfTools.Load()
   at DinkToPdf.BasicConverter.Convert(IDocument document)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at DinkToPdf.SynchronizedConverter.Invoke[TResult](Func`1 delegate)
   at Magicodes.ExporterAndImporter.Pdf.PdfExporter.ExportPdf(PdfExporterAttribute pdfExporterAttribute, String htmlString)
   at Magicodes.ExporterAndImporter.Pdf.PdfExporter.ExportBytesByTemplate[T](T data, String template)
   at WebApplication3.Controllers.HomeController.hetong() in E:\tempcode\temp\WebApplication3\Controllers\HomeController.cs:line 119
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at WebApplication3.Controllers.HomeController.Index() in E:\tempcode\temp\WebApplication3\Controllers\HomeController.cs:line 21
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Unable to load shared library 'wkhtmltox' or one of its dependencies. In order to help diagnose loadvironment variable: libwkhtmltox: cannot open shared object file: No such file or directory) ---> System.DllNotFoundException: Unable to load shared library 'wkhtmltox' or one of its g problems, consider setting the LD_DEBUG environment variable: libwkhtmltox: cannot open shared object file: No such file or directory
   at DinkToPdf.WkHtmlToXBindings.wkhtmltopdf_init(Int32 useGraphics)
   at DinkToPdf.WkHtmlModule.wkhtmltopdf_init(Int32 useGraphics)
   at DinkToPdf.PdfTools.Load()
   at DinkToPdf.BasicConverter.Convert(IDocument document)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at DinkToPdf.SynchronizedConverter.Invoke[TResult](Func`1 delegate)
   at Magicodes.ExporterAndImporter.Pdf.PdfExporter.ExportPdf(PdfExporterAttribute pdfExporterAttribute, String htmlString)
   at Magicodes.ExporterAndImporter.Pdf.PdfExporter.ExportBytesByTemplate[T](T data, String template)
   at WebApplication3.Controllers.HomeController.hetong() in E:\tempcode\temp\WebApplication3\Controllers\HomeController.cs:line 119
---> (Inner Exception #0) System.DllNotFoundException: Unable to load shared library 'wkhtmltox' or one of its dependencies. In order to help diagnose loading problems, consider settiltox: cannot open shared object file: No such file or directory
   at DinkToPdf.WkHtmlToXBindings.wkhtmltopdf_init(Int32 useGraphics)
   at DinkToPdf.WkHtmlModule.wkhtmltopdf_init(Int32 useGraphics)
   at DinkToPdf.PdfTools.Load()
   at DinkToPdf.BasicConverter.Convert(IDocument document)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---

**Comment by hueifeng** [comment]
Need to added `libgdiplus` to works!  #115

**Comment by cnmediar** [comment]
![image](https://user-images.githubusercontent.com/18731551/86610586-230f3480-bfe0-11ea-87a1-fbfc2bf07f98.png)

(1/2): epel/x86_64/updateinfo                                                                                                                                  | 1.0 MB  00:00:00     
(2/2): epel/x86_64/primary_db                                                                                                                                  | 6.8 MB  00:00:00     
Package libgdiplus-2.10-10.el7.x86_64 already installed and latest version

libgdiplus 这个库已经安装了。可是还是出现问题 ，我的是centos 7

**Comment by yeibl** [comment]
我也出现这样的问题

**Comment by xin-lai** [comment]
目前我们在Linux 容器下没有问题，直接在CentOS 7下面使用，我们还需调测。

**Comment by hueifeng** [comment]
You can use the following method:

```
   <PackageReference Include="Magicodes.IE.Pdf" >
      <CopyToOutputDirectory>runtimes/*</CopyToOutputDirectory>
    </PackageReference>
```
or
```

    <PackageReference Include="Magicodes.IE.Pdf" Version="2.3.0-beta3">
            <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

**Comment by hueifeng** [comment]
Reopen this issue?
