### ISSUE TITLE
在Maui Blazor App 中使用  导入正常 导出报错!

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/Magicodes.IE#407]
使用方法
``````
var res = await exporter.Export(fileName,ndata);
``````
报错内容
``````
{System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: libgdiplus
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
   at OfficeOpenXml.ExcelColumn.AutoFit()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].AddStyle()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].AddHeaderAndStyles()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].Export(ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.ExportAsByteArray[IdentityExporter](ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.<Export>d__5`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MauiApp2.Pages.ActiveList.SaveExcel() in D:\2022\learn\MauiBlazorDemo-main\MauiBlazorDemo-main\Pages\ActiveList.razor.cs:line 34}
``````

**Comment by lhtuling** [comment]
搜资料发现有的说是图片处理方面导致的
但是我这个导出是纯文字信息,不包括图片相关信息!

**Comment by lhtuling** [comment]
引用System.Drawing.Common 
报错:
``````
在非windows平台上不支持System.Drawing.Common。更多信息请参见https://aka.ms/systemdrawingnonwindows。”
``````

**Comment by hueifeng** [comment]
> 引用System.Drawing.Common 报错:
> 
> ```
> 在非windows平台上不支持System.Drawing.Common。更多信息请参见https://aka.ms/systemdrawingnonwindows。”
> ```

可以先以配置runtimeconfig.json 的方式去使用
```
{
   "configProperties": {
      "System.Drawing.EnableUnixSupport": true
   }
}
```

或者在csproj文件中添加如下内容。

```
<RuntimeHostConfigurationOption Include="System.Drawing.EnableUnixSupport" Value="true" />
```

[SkiaSharp](https://github.com/mono/SkiaSharp)和[ImageSharp](https://github.com/SixLabors/ImageSharp)对于office的中的图像编解码器有些缺失，目前不能快速的切换

**Comment by lhtuling** [comment]
> https://aka.ms/systemdrawingnonwindows
在csproj文件中添加如下内容。
<RuntimeHostConfigurationOption Include="System.Drawing.EnableUnixSupport" Value="true" />

还会报错  有其他的办法么?
``````
{System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: libgdiplus
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
   at OfficeOpenXml.ExcelColumn.AutoFit()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].AddStyle()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].AddHeaderAndStyles()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].Export(ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.ExportAsByteArray[IdentityExporter](ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.<Export>d__5`1[[MauiApp2.Model.IdentityExporter, MauiApp2, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at MauiApp2.Pages.ActiveList.SaveExcel() in D:\2022\learn\MauiBlazorDemo-main\MauiBlazorDemo-main\Pages\ActiveList.razor.cs:line 45}
``````

**Comment by lhtuling** [comment]
完美解决  只需要在模型上设置下导出不要自动适应就ok了
![image](https://user-images.githubusercontent.com/44140500/170818055-f82d8eb3-6155-4cd1-8257-4a093c1f9d06.png)
感谢大佬 @hueifeng 的辛苦测试!
