### ISSUE TITLE
官方Docker镜像中运行报错 The type initializer for 'SkiaSharp.SKFontStyle' threw an exception.

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/Magicodes.IE#468]
### Expected behaviour
ExcelExpoter.ExportAsByteArray正常导出

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant.
官方Docker镜像中运行报错 The type initializer for 'SkiaSharp.SKFontStyle' threw an exception.
```
   at OfficeOpenXml.ExcelRangeBase.GetAvailableFont(String text)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double minimumWidth, Double maximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
   at OfficeOpenXml.ExcelColumn.AutoFit()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.AddStyle()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.AddHeaderAndStyles()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.Export(ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.ExportAsByteArray[T](ICollection`1 dataItems)
```

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [x] Magicodes.IE.Excel
- [ ] Magicodes.IE.Pdf
- [ ] Magicodes.IE.Word
- [ ] Magicodes.IE.Csv
- [ ] Magicodes.IE.Html
- [ ] Magicodes.IE.AspNetCore

#### package versions
<PackageReference Include="Magicodes.IE.Excel" Version="2.7.0" />

### So how can we reproduce this?
可以，在`FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base`镜像中导出即可看到异常

**Comment by sampsonye** [comment]
根据 #463 
安装`Install-Package SkiaSharp.NativeAssets.Linux.NoDependencies` 后问题解决
