### ISSUE TITLE
magicodes.ie.excel.aspnetcore 2.7.4.5在WindowServier 2012R2下运行The type initializer for 'SkiaSharp.SKFontStyle' threw an exception. 

### ISSUE THREAD

**Issue by Sheldon-NULL** [dotnetcore/Magicodes.IE#548]
### Expected behaviour
生成Excel文件的时候报错
#463 #468 报错信息应该是一样的，但是服务器环境是WinServer;
ps:本地window10环境没有问题
- [ ] Magicodes.IE.Excel
- [ ] Magicodes.IE.Pdf
- [ ] Magicodes.IE.Word
- [ ] Magicodes.IE.Csv
- [ ] Magicodes.IE.Html
- [ *] Magicodes.IE.AspNetCore

#### package versions
Example: Magicodes.IE.Excel 2.2.2, Magicodes.IE.Pdf 1.0

#### StackMsg:
错误消息: The type initializer for 'SkiaSharp.SKFontStyle' threw an exception.
            堆栈信息:      at OfficeOpenXml.ExcelRangeBase.GetAvailableFont(String text)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double minimumWidth, Double maximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.AddHeaderAndStyles()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.Export(ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.ExportAsByteArray[T](ICollection`1 dataItems)

**Comment by Sheldon-NULL** [comment]
单独安装SkiaSharp.NativeAssets.Win32，没有作用。
升级到magicodes.ie.excel.aspnetcore 2.7.4.5.1 ，没有作用

**Comment by hueifeng** [comment]
windows server哪个版本？

**Comment by Sheldon-NULL** [comment]
![image](https://github.com/dotnetcore/Magicodes.IE/assets/83170675/077d5a08-277b-48f4-b767-f45f55f06145)

**Comment by Sheldon-NULL** [comment]
@hueifeng 
![image](https://github.com/dotnetcore/Magicodes.IE/assets/83170675/2253f124-51b1-4bb1-aec1-1a6c471995b9)
DataServer的版本可以，很奇怪。是包的兼容性问题吗

**Comment by Sheldon-NULL** [comment]
少哪个runtimes文件？libskiasharp这个dll也有的。不好复现，自己的云测试服务器都没复现出来，就是在生产环境出问题了

**Comment by hueifeng** [comment]
2.8.2 已将 SkiaSharp 升级到 3.119.1,2.8.5 在此基础上继续优化(Linux 下 AutoFit 字体测量预加载 SKTypeface 缓存)。

请更新到 2.8.5 后确认问题是否仍存在。
NuGet: Magicodes.IE.Excel 2.8.5
Release notes: https://github.com/dotnetcore/Magicodes.IE/blob/master/RELEASE.md#285

若仍复现,请附:操作系统版本、是否安装 SkiaSharp native runtime(libSkiaSharp)、完整异常堆栈。
