### ISSUE TITLE
Magicodes.IE 和npoi冲突

### ISSUE THREAD

**Issue by huguodong** [dotnetcore/Magicodes.IE#557]
### Expected behaviour
Magicodes.IE 和npoi冲突，报错

System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream(System.String)'.
   at OfficeOpenXml.Utils.RecyclableMemoryStream.GetStream()
   at OfficeOpenXml.ExcelPackage.ConstructNewFile(String password)
   at OfficeOpenXml.ExcelPackage..ctor()
   at Magicodes.ExporterAndImporter.Excel.Utility.ImportHelper`1.GenerateTemplateByte()
   at Magicodes.ExporterAndImporter.Excel.ExcelImporter.GenerateTemplateBytes[T]()

**Comment by ForeverRG** [comment]
我也遇到了这个错误，请问应该怎么解决？

**Comment by huguodong** [comment]
> 我也遇到了这个错误，请问应该怎么解决？

降级npoi到和mag一样的版本

**Comment by ForeverRG** [comment]
> > 我也遇到了这个错误，请问应该怎么解决？
> 
> 降级npoi到和mag一样的版本

我检查了下，没用npoi这个包，但还是报了这个错，不折腾了，换其他库了，谢谢了

**Comment by huguodong** [comment]
> > > 我也遇到了这个错误，请问应该怎么解决？
> > 
> > 
> > 降级npoi到和mag一样的版本
> 
> 我检查了下，没用npoi这个包，但还是报了这个错，不折腾了，换其他库了，谢谢了

那怎么会冲突呢，肯定是有包冲突了，我是同时用了npoi和mag，你可以逐步排查是哪个包冲突了

**Comment by hueifeng** [comment]
已在 2.8.5 修复,请更新到最新版验证。

修复说明:NPOI 升级至 2.8.0 并移除 System.Drawing.Common 依赖,SharpZipLib 升至 1.4.2,传递依赖冲突已消除,现在可以在同一项目中共用 NPOI。

Release notes: https://github.com/dotnetcore/Magicodes.IE/blob/master/RELEASE.md#285
NuGet: Magicodes.IE.Excel 2.8.5

如仍有冲突请重开并附 `dotnet list package --include-transitive` 输出。
