### ISSUE TITLE
2.2.0-beta2版本以Append方式导出多个sheet时，发生“Tablename is not unique”错误

### ISSUE THREAD

**Issue by Superllb93** [dotnetcore/Magicodes.IE#66]
2.2.0-beta2版本以Append方式导出多个sheet时，当Append的ICollection<T>均为空集合时，报 “Tablename is not unique”错误，比如：

`new ExcelExporter().Append(new List<Student>()).Append(new List<Teacher>()).ExportAppendData("test.xlsx");`

![image](https://user-images.githubusercontent.com/49815294/77497863-4a0a8600-6e89-11ea-8683-0a7dcd17ba0e.png)

详细错误信息如下：
```
System.ArgumentException
  HResult=0x80070057
  Message=Tablename is not unique
  Source=EPPlus
  StackTrace:
   at OfficeOpenXml.Table.ExcelTableCollection.Add(ExcelAddressBase Range, String Name)
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.AddHeader()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.AddHeaderAndStyles()
   at Magicodes.ExporterAndImporter.Excel.Utility.ExportHelper`1.Export(ICollection`1 dataItems)
   at Magicodes.ExporterAndImporter.Excel.ExcelExporter.Append[T](ICollection`1 dataItems)
   at Magicodes.IE.Excel.Program.Export() in E:\Technology\Magicodes.IE.Excel\Magicodes.IE.Excel\Program.cs:line 29
   at Magicodes.IE.Excel.Program.Main(String[] args) in E:\Technology\Magicodes.IE.Excel\Magicodes.IE.Excel\Program.cs:line 15
```

@xin-lai  请帮忙尽快解决，谢谢

**Comment by xin-lai** [comment]
收到。这种情形我们确实没有考虑。

**Comment by Superllb93** [comment]
可对`ExportHelper`类里的`AddHeader()`方法进行如下修改

![image](https://user-images.githubusercontent.com/49815294/77510321-6dddc400-6ea9-11ea-9041-2e5d6b4cc107.png)

亲测可用 @xin-lai ，本地代码无法push，请帮忙验证，

**Comment by xin-lai** [comment]
收到，这个问题我们是清楚如何处理的。

**Comment by xin-lai** [comment]
非常感谢！

**Comment by xin-lai** [comment]
2020.03.26
【Nuget】版本更新到2.2.0-beta4
【Excel多Sheet导出】修复#66，并添加单元测试

**Comment by zoe62** [comment]
修复之后，如果两个都是ICollection均为空集合，无异常，如第二个ICollection为空集合，仍然报 “Tablename is not unique”错误

**Comment by zoe62** [comment]
@xin-lai

**Comment by qcjxberin** [comment]
Excel多Sheet导出  有没有Demo的？正好在找这个
